version: '3'

services:

  db:
    container_name: notejam-db
    image: mysql:5.7
    restart: "no"
    environment:
      MYSQL_ROOT_PASSWORD: 1234qwer
    ports:
      - 3306
    volumes:
      - "./sql:/docker-entrypoint-initdb.d"

  app:
    container_name: notejam-app
    restart: "no"
    image: notejam-sqlapp
    depends_on:
      - "db"
    environment:
      MYSQL_HOST: "notejam-db"
      MYSQL_ROOT_PASSWORD: 1234qwer
      MYSQL_TCP_PORT: 3306
      NODE_ENV: development
      NOTEJAM_HOST: "notejam-app"
      NOTEJAM_PORT: 3000
    ports:
      - 3000:3000

volumes:
  sql:
  notejam: